# Generated by Django 6.0.7 on 2026-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default.jpg', null=True, upload_to='avatar/'),
        ),
    ]
