# Generated by Django 6.0.7 on 2026-07-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='note',
        ),
    ]
