# Generated by Django 6.0.7 on 2026-07-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
