# Generated by Django 6.0.7 on 2026-08-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('groups', '0006_alter_groupmember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_left', 'Member Left'), ('expense_created', 'Expense Created'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settlement_created', 'Settlement Created')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='groups.group'),
        ),
    ]
