# Generated by Django 6.0.7 on 2026-08-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_action_alter_activity_group'),
        ('groups', '0006_alter_groupmember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group'),
        ),
    ]
