# Generated by Django 6.0.7 on 2026-07-26 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense_participant',
            new_name='ExpenseParticipant',
        ),
    ]
