# Generated by Django 6.0.7 on 2026-07-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_remove_expenseparticipant_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
    ]
